/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#include "Custom.h"

static asn_TYPE_member_t asn_MBR_Custom_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, releaseCounter),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Natural,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"releaseCounter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, hardwareIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hardwareIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, ecuIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ecuIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, hardwareVersion),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Version,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hardwareVersion"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, installMethod),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InstallMethodType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"installMethod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, imageFormat),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ImageFormatType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageFormat"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, isCompressed),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompressType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"isCompressed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Custom, dependency),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Natural,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dependency"
		},
	{ ATF_POINTER, 1, offsetof(struct Custom, delta),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delta"
		},
};
static const ber_tlv_tag_t asn_DEF_Custom_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Custom_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* releaseCounter */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hardwareIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ecuIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* hardwareVersion */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* installMethod */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* imageFormat */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* isCompressed */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* dependency */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* delta */
};
static asn_SEQUENCE_specifics_t asn_SPC_Custom_specs_1 = {
	sizeof(struct Custom),
	offsetof(struct Custom, _asn_ctx),
	asn_MAP_Custom_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	8,	/* Start extensions */
	10	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Custom = {
	"Custom",
	"Custom",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Custom_tags_1,
	sizeof(asn_DEF_Custom_tags_1)
		/sizeof(asn_DEF_Custom_tags_1[0]), /* 1 */
	asn_DEF_Custom_tags_1,	/* Same as above */
	sizeof(asn_DEF_Custom_tags_1)
		/sizeof(asn_DEF_Custom_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Custom_1,
	9,	/* Elements count */
	&asn_SPC_Custom_specs_1	/* Additional specs */
};

