/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#include "ECUVersionManifestSigned.h"

static int check_permitted_alphabet_5(const void *sptr) {
	/* The underlying type is VisibleString */
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!(cv >= 32 && cv <= 126)) return -1;
	}
	return 0;
}

static int
memb_securityAttack_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const VisibleString_t *st = (const VisibleString_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 1024)
		 && !check_permitted_alphabet_5(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_ECUVersionManifestSigned_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ECUVersionManifestSigned, ecuIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Identifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ecuIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECUVersionManifestSigned, previousTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTCDateTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"previousTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECUVersionManifestSigned, currentTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTCDateTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"currentTime"
		},
	{ ATF_POINTER, 1, offsetof(struct ECUVersionManifestSigned, securityAttack),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		memb_securityAttack_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"securityAttack"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECUVersionManifestSigned, installedImage),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Target,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"installedImage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ECUVersionManifestSigned, state),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SwClusterStateType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"state"
		},
};
static const ber_tlv_tag_t asn_DEF_ECUVersionManifestSigned_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ECUVersionManifestSigned_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ecuIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* previousTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* currentTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* securityAttack */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* installedImage */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* state */
};
static asn_SEQUENCE_specifics_t asn_SPC_ECUVersionManifestSigned_specs_1 = {
	sizeof(struct ECUVersionManifestSigned),
	offsetof(struct ECUVersionManifestSigned, _asn_ctx),
	asn_MAP_ECUVersionManifestSigned_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ECUVersionManifestSigned = {
	"ECUVersionManifestSigned",
	"ECUVersionManifestSigned",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ECUVersionManifestSigned_tags_1,
	sizeof(asn_DEF_ECUVersionManifestSigned_tags_1)
		/sizeof(asn_DEF_ECUVersionManifestSigned_tags_1[0]), /* 1 */
	asn_DEF_ECUVersionManifestSigned_tags_1,	/* Same as above */
	sizeof(asn_DEF_ECUVersionManifestSigned_tags_1)
		/sizeof(asn_DEF_ECUVersionManifestSigned_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ECUVersionManifestSigned_1,
	6,	/* Elements count */
	&asn_SPC_ECUVersionManifestSigned_specs_1	/* Additional specs */
};

