/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Filename_H_
#define	_Filename_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Filename */
typedef VisibleString_t	 Filename_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Filename;
asn_struct_free_f Filename_free;
asn_struct_print_f Filename_print;
asn_constr_check_f Filename_constraint;
ber_type_decoder_f Filename_decode_ber;
der_type_encoder_f Filename_encode_der;
xer_type_decoder_f Filename_decode_xer;
xer_type_encoder_f Filename_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Filename_H_ */
#include <asn_internal.h>
