/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_HashFunction_H_
#define	_HashFunction_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HashFunction {
	HashFunction_sha224	= 0,
	HashFunction_sha256	= 1,
	HashFunction_sha384	= 2,
	HashFunction_sha512	= 3,
	HashFunction_sha512_224	= 4,
	HashFunction_sha512_256	= 5
	/*
	 * Enumeration is extensible
	 */
} e_HashFunction;

/* HashFunction */
typedef long	 HashFunction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HashFunction;
asn_struct_free_f HashFunction_free;
asn_struct_print_f HashFunction_print;
asn_constr_check_f HashFunction_constraint;
ber_type_decoder_f HashFunction_decode_ber;
der_type_encoder_f HashFunction_encode_der;
xer_type_decoder_f HashFunction_decode_xer;
xer_type_encoder_f HashFunction_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HashFunction_H_ */
#include <asn_internal.h>
