/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_ImageFormatType_H_
#define	_ImageFormatType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ImageFormatType {
	ImageFormatType_binary	= 0,
	ImageFormatType_srecord	= 1
} e_ImageFormatType;

/* ImageFormatType */
typedef long	 ImageFormatType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImageFormatType;
asn_struct_free_f ImageFormatType_free;
asn_struct_print_f ImageFormatType_print;
asn_constr_check_f ImageFormatType_constraint;
ber_type_decoder_f ImageFormatType_decode_ber;
der_type_encoder_f ImageFormatType_encode_der;
xer_type_decoder_f ImageFormatType_decode_xer;
xer_type_encoder_f ImageFormatType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ImageFormatType_H_ */
#include <asn_internal.h>
