/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Mappings_H_
#define	_Mappings_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Mapping;

/* Mappings */
typedef struct Mappings {
	A_SEQUENCE_OF(struct Mapping) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Mappings_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Mappings;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Mapping.h"

#endif	/* _Mappings_H_ */
#include <asn_internal.h>
