/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_MultiRole_H_
#define	_MultiRole_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StrictFilename.h"
#include "Length.h"
#include "Keyids.h"
#include "Threshold.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MultiRole */
typedef struct MultiRole {
	StrictFilename_t	 rolename;
	Length_t	 numberOfKeyids;
	Keyids_t	 keyids;
	Threshold_t	 threshold;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiRole;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiRole_H_ */
#include <asn_internal.h>
