/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_OctetString_H_
#define	_OctetString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OctetString */
typedef OCTET_STRING_t	 OctetString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OctetString;
asn_struct_free_f OctetString_free;
asn_struct_print_f OctetString_print;
asn_constr_check_f OctetString_constraint;
ber_type_decoder_f OctetString_decode_ber;
der_type_encoder_f OctetString_encode_der;
xer_type_decoder_f OctetString_decode_xer;
xer_type_encoder_f OctetString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OctetString_H_ */
#include <asn_internal.h>
