/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Paths_H_
#define	_Paths_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Path.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Paths */
typedef struct Paths {
	A_SEQUENCE_OF(Path_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Paths_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Paths;

#ifdef __cplusplus
}
#endif

#endif	/* _Paths_H_ */
#include <asn_internal.h>
