/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_PathsToRoles_H_
#define	_PathsToRoles_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Length.h"
#include "Paths.h"
#include "MultiRoles.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PathsToRoles */
typedef struct PathsToRoles {
	Length_t	 numberOfPaths;
	Paths_t	 paths;
	Length_t	 numberOfRoles;
	MultiRoles_t	 roles;
	BOOLEAN_t	*terminating	/* DEFAULT FALSE */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathsToRoles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathsToRoles;

#ifdef __cplusplus
}
#endif

#endif	/* _PathsToRoles_H_ */
#include <asn_internal.h>
