/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Positive_H_
#define	_Positive_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Positive */
typedef long	 Positive_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Positive;
asn_struct_free_f Positive_free;
asn_struct_print_f Positive_print;
asn_constr_check_f Positive_constraint;
ber_type_decoder_f Positive_decode_ber;
der_type_encoder_f Positive_encode_der;
xer_type_decoder_f Positive_decode_xer;
xer_type_encoder_f Positive_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Positive_H_ */
#include <asn_internal.h>
