/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_PublicKeyType_H_
#define	_PublicKeyType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PublicKeyType {
	PublicKeyType_rsa_2048	= 0,
	PublicKeyType_ed25519	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PublicKeyType;

/* PublicKeyType */
typedef long	 PublicKeyType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicKeyType;
asn_struct_free_f PublicKeyType_free;
asn_struct_print_f PublicKeyType_print;
asn_constr_check_f PublicKeyType_constraint;
ber_type_decoder_f PublicKeyType_decode_ber;
der_type_encoder_f PublicKeyType_encode_der;
xer_type_decoder_f PublicKeyType_decode_xer;
xer_type_encoder_f PublicKeyType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicKeyType_H_ */
#include <asn_internal.h>
