/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_PublicKeys_H_
#define	_PublicKeys_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PublicKey;

/* PublicKeys */
typedef struct PublicKeys {
	A_SEQUENCE_OF(struct PublicKey) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicKeys_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicKeys;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PublicKey.h"

#endif	/* _PublicKeys_H_ */
#include <asn_internal.h>
