/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_PublicKey_H_
#define	_PublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Keyid.h"
#include "PublicKeyType.h"
#include "OctetString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PublicKey */
typedef struct PublicKey {
	Keyid_t	 publicKeyid;
	PublicKeyType_t	 publicKeyType;
	OctetString_t	 publicKeyValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicKey;

#ifdef __cplusplus
}
#endif

#endif	/* _PublicKey_H_ */
#include <asn_internal.h>
