/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_RepositoryNames_H_
#define	_RepositoryNames_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RepositoryName.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RepositoryNames */
typedef struct RepositoryNames {
	A_SEQUENCE_OF(RepositoryName_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RepositoryNames_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RepositoryNames;

#ifdef __cplusplus
}
#endif

#endif	/* _RepositoryNames_H_ */
#include <asn_internal.h>
