/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Repositories_H_
#define	_Repositories_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Repository;

/* Repositories */
typedef struct Repositories {
	A_SEQUENCE_OF(struct Repository) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Repositories_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Repositories;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Repository.h"

#endif	/* _Repositories_H_ */
#include <asn_internal.h>
