/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_RepositoryName_H_
#define	_RepositoryName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "StrictFilename.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RepositoryName */
typedef StrictFilename_t	 RepositoryName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RepositoryName;
asn_struct_free_f RepositoryName_free;
asn_struct_print_f RepositoryName_print;
asn_constr_check_f RepositoryName_constraint;
ber_type_decoder_f RepositoryName_decode_ber;
der_type_encoder_f RepositoryName_encode_der;
xer_type_decoder_f RepositoryName_decode_xer;
xer_type_encoder_f RepositoryName_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RepositoryName_H_ */
#include <asn_internal.h>
