/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_SignatureMethod_H_
#define	_SignatureMethod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignatureMethod {
	SignatureMethod_rsassa_pss	= 0,
	SignatureMethod_ed25519	= 1
	/*
	 * Enumeration is extensible
	 */
} e_SignatureMethod;

/* SignatureMethod */
typedef long	 SignatureMethod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignatureMethod;
asn_struct_free_f SignatureMethod_free;
asn_struct_print_f SignatureMethod_print;
asn_constr_check_f SignatureMethod_constraint;
ber_type_decoder_f SignatureMethod_decode_ber;
der_type_encoder_f SignatureMethod_encode_der;
xer_type_decoder_f SignatureMethod_decode_xer;
xer_type_encoder_f SignatureMethod_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SignatureMethod_H_ */
#include <asn_internal.h>
