/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_SignedBody_H_
#define	_SignedBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RootMetadata.h"
#include "TargetsMetadata.h"
#include "SnapshotMetadata.h"
#include "TimestampMetadata.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignedBody_PR {
	SignedBody_PR_NOTHING,	/* No components present */
	SignedBody_PR_rootMetadata,
	SignedBody_PR_targetsMetadata,
	SignedBody_PR_snapshotMetadata,
	SignedBody_PR_timestampMetadata
} SignedBody_PR;

/* SignedBody */
typedef struct SignedBody {
	SignedBody_PR present;
	union SignedBody_u {
		RootMetadata_t	 rootMetadata;
		TargetsMetadata_t	 targetsMetadata;
		SnapshotMetadata_t	 snapshotMetadata;
		TimestampMetadata_t	 timestampMetadata;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedBody;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedBody_H_ */
#include <asn_internal.h>
