/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_SnapshotMetadataFiles_H_
#define	_SnapshotMetadataFiles_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SnapshotMetadataFile;

/* SnapshotMetadataFiles */
typedef struct SnapshotMetadataFiles {
	A_SEQUENCE_OF(struct SnapshotMetadataFile) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SnapshotMetadataFiles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SnapshotMetadataFiles;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SnapshotMetadataFile.h"

#endif	/* _SnapshotMetadataFiles_H_ */
#include <asn_internal.h>
