/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_SwClusterStateType_H_
#define	_SwClusterStateType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SwClusterStateType {
	SwClusterStateType_kunregistered	= 0,
	SwClusterStateType_kPresent	= 1,
	SwClusterStateType_kAdded	= 2,
	SwClusterStateType_kUpdated	= 3,
	SwClusterStateType_kRemoved	= 4
} e_SwClusterStateType;

/* SwClusterStateType */
typedef long	 SwClusterStateType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SwClusterStateType;
asn_struct_free_f SwClusterStateType_free;
asn_struct_print_f SwClusterStateType_print;
asn_constr_check_f SwClusterStateType_constraint;
ber_type_decoder_f SwClusterStateType_decode_ber;
der_type_encoder_f SwClusterStateType_encode_der;
xer_type_decoder_f SwClusterStateType_decode_xer;
xer_type_encoder_f SwClusterStateType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SwClusterStateType_H_ */
#include <asn_internal.h>
