/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_TargetAndCustom_H_
#define	_TargetAndCustom_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Target.h"
#include "Custom.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TargetAndCustom */
typedef struct TargetAndCustom {
	Target_t	 target;
	Custom_t	 custom;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TargetAndCustom_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TargetAndCustom;

#ifdef __cplusplus
}
#endif

#endif	/* _TargetAndCustom_H_ */
#include <asn_internal.h>
