/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_Threshold_H_
#define	_Threshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Positive.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Threshold */
typedef Positive_t	 Threshold_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Threshold;
asn_struct_free_f Threshold_free;
asn_struct_print_f Threshold_print;
asn_constr_check_f Threshold_constraint;
ber_type_decoder_f Threshold_decode_ber;
der_type_encoder_f Threshold_encode_der;
xer_type_decoder_f Threshold_decode_xer;
xer_type_encoder_f Threshold_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Threshold_H_ */
#include <asn_internal.h>
