/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#include "TopLevelRole.h"

static asn_TYPE_member_t asn_MBR_TopLevelRole_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRole, role),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoleType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"role"
		},
	{ ATF_POINTER, 2, offsetof(struct TopLevelRole, numberOfURLs),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Length,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfURLs"
		},
	{ ATF_POINTER, 1, offsetof(struct TopLevelRole, urls),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URLs,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"urls"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRole, numberOfKeyids),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Length,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberOfKeyids"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRole, keyids),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Keyids,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyids"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TopLevelRole, threshold),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Threshold,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"threshold"
		},
};
static const ber_tlv_tag_t asn_DEF_TopLevelRole_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TopLevelRole_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* role */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfURLs */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* urls */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* numberOfKeyids */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* keyids */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_TopLevelRole_specs_1 = {
	sizeof(struct TopLevelRole),
	offsetof(struct TopLevelRole, _asn_ctx),
	asn_MAP_TopLevelRole_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TopLevelRole = {
	"TopLevelRole",
	"TopLevelRole",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TopLevelRole_tags_1,
	sizeof(asn_DEF_TopLevelRole_tags_1)
		/sizeof(asn_DEF_TopLevelRole_tags_1[0]), /* 1 */
	asn_DEF_TopLevelRole_tags_1,	/* Same as above */
	sizeof(asn_DEF_TopLevelRole_tags_1)
		/sizeof(asn_DEF_TopLevelRole_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TopLevelRole_1,
	6,	/* Elements count */
	&asn_SPC_TopLevelRole_specs_1	/* Additional specs */
};

