/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_TopLevelRoles_H_
#define	_TopLevelRoles_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TopLevelRole;

/* TopLevelRoles */
typedef struct TopLevelRoles {
	A_SEQUENCE_OF(struct TopLevelRole) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TopLevelRoles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TopLevelRoles;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TopLevelRole.h"

#endif	/* _TopLevelRoles_H_ */
#include <asn_internal.h>
