/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "UptaneASN1Definitions"
 * 	found in "ota_metadata.asn1"
 */

#ifndef	_URL_H_
#define	_URL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* URL */
typedef VisibleString_t	 URL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_URL;
asn_struct_free_f URL_free;
asn_struct_print_f URL_print;
asn_constr_check_f URL_constraint;
ber_type_decoder_f URL_decode_ber;
der_type_encoder_f URL_encode_der;
xer_type_decoder_f URL_decode_xer;
xer_type_encoder_f URL_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _URL_H_ */
#include <asn_internal.h>
